#Expyriment 0.9.0 (Python 2.7.15), .xpe-file, coding: UTF-8
#date: Wed Sep 19 2018 22:53:11
#sha1: 4460d5
#modules: 
#display: size=(1440, 900), window_mode=False, open_gl=2
#os: ('Darwin', 'Lynns-MacBook-Air.local', '17.2.0', 'Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64', 'x86_64', 'i386')
Time,Type,Event,Value,Detail,Detail2
10486,design,log,
#design: #exp: First Experiment
#design: block_cnt,block_id,trial_cnt,trial_id
10486,design,logged,
10486,Experiment,started
11353,Video,playing,videoPairs/pair0.mp4
11355,stderr,received,'Traceback (most recent call last):'
11355,stderr,received,'  File "/Users/lynn/Desktop/AMT Research assistantship/AMT_results/AMTproject_consistency/Experiment_100pairs.py", line 44, in <module>'
11355,stderr,received,'    my_video1.update()'
11356,stderr,received,"NameError: name 'my_video1' is not defined"
