#Expyriment 0.9.0 (Python 2.7.15), .xpe-file, coding: UTF-8
#date: Wed Sep 19 2018 13:22:22
#sha1: 8f8bfd
#modules: 
#display: size=(1440, 900), window_mode=False, open_gl=2
#os: ('Darwin', 'Lynns-MacBook-Air.local', '17.2.0', 'Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64', 'x86_64', 'i386')
Time,Type,Event,Value,Detail,Detail2
10997,design,log,
#design: #exp: First Experiment
#design: block_cnt,block_id,trial_cnt,trial_id
10997,design,logged,
10997,Experiment,started
11064,stdout,received,'videos/7ZnijRlK5-E.000.mp4'
12603,stdout,received,'size 1 (1280, 720)'
12603,stdout,received,'size 2 (1280, 720)'
12604,Video,playing,videos/zEyRyTnIw5I.004.mp4
12606,Video,playing,videos/7ZnijRlK5-E.000.mp4
12608,stderr,received,'Traceback (most recent call last):'
12608,stderr,received,'  File "/Users/lynn/Desktop/AMT Research assistantship/AMT_results/AMTproject_consistency/Experiment_100pairs.py", line 69, in <module>'
12609,stderr,received,'    my_video1.present(update=False)'
12609,stderr,received,"TypeError: present() got an unexpected keyword argument 'update'"
